"""initial schema: assets, inspections, media_files, detections

Revision ID: 9998b9decd4a
Revises: 
Create Date: 2026-08-30 01:55:48.820768
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9998b9decd4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('bridge', 'building', 'road', 'dam', 'pipeline', 'tunnel', 'other', name='asset_type'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name='ck_asset_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name='ck_asset_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_asset_type', 'assets', ['asset_type'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='inspection_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspections_asset_id', 'inspections', ['asset_id'], unique=False)
    op.create_index('ix_inspections_status', 'inspections', ['status'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='media_type'), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name='ck_media_size_positive'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_media_files_inspection_id', 'media_files', ['inspection_id'], unique=False)
    op.create_index('ix_media_files_processed', 'media_files', ['processed'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_file_id', sa.UUID(), nullable=False),
    sa.Column('defect_class', sa.Enum('crack', 'corrosion', 'surface_damage', 'missing_component', name='defect_class'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_width', sa.Float(), nullable=False),
    sa.Column('bbox_height', sa.Float(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('normalized_area', sa.Float(), nullable=True),
    sa.Column('class_weight', sa.Float(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('severity_band', sa.Enum('low', 'medium', 'high', 'critical', name='severity_band'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bbox_x >= 0 AND bbox_y >= 0 AND bbox_width > 0 AND bbox_height > 0', name='ck_detection_bbox_positive'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_detection_confidence'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detections_defect_class', 'detections', ['defect_class'], unique=False)
    op.create_index('ix_detections_media_file_id', 'detections', ['media_file_id'], unique=False)
    op.create_index('ix_detections_severity_band', 'detections', ['severity_band'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detections_severity_band', table_name='detections')
    op.drop_index('ix_detections_media_file_id', table_name='detections')
    op.drop_index('ix_detections_defect_class', table_name='detections')
    op.drop_table('detections')
    op.drop_index('ix_media_files_processed', table_name='media_files')
    op.drop_index('ix_media_files_inspection_id', table_name='media_files')
    op.drop_table('media_files')
    op.drop_index('ix_inspections_status', table_name='inspections')
    op.drop_index('ix_inspections_asset_id', table_name='inspections')
    op.drop_table('inspections')
    op.drop_index('ix_assets_asset_type', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
